### ISSUE TITLE
Request for Guidelines on Display Conditions for the GitHub Repository Information Card

### ISSUE THREAD

**Issue by 4444TENSEI** [JonathanXDR/Application-Website-Frontend#66]
Hi Jonathan,

I apologize for the inconvenience.  I’m having trouble displaying GitHub repository cards in the ProjectsSection. vue component located at components\containers\.

I’ve set up GITHUB_TOKEN and GITHUB_REPO_OWNER in the .env.local file at the root, and I can retrieve the repository information during debugging.  However, the CardItem. vue component in components\common\ is not rendering the GitHub repository information for the “Personal Project” and “School Project” sections of the webpage.

Is there something else I need to configure or check to make this work?

Thank you for your assistance.

**Comment by JonathanXDR** [comment]
Hello there,

The problem seems to be related to the condition on line 61 of the `components/containers/ProjectsSection.vue` component. The condition checks if `projects.school.length` is defined. However, in this case, I’ve applied a regex filter to include only certain GitHub repositories based on their names (which follow a specific naming convention used for school projects). Since your repositories don't match this regex, `projects.school` is undefined, and the condition fails.

To resolve this, you can remove the `&& projects.school.length` condition from line 61. This should allow the GitHub repository information to render correctly in the “Personal Project” and “School Project” sections.

If you need further assistance or if there are any other issues, feel free to reach out.

Best regards,  
Jonathan

**Comment by 4444TENSEI** [comment]
> Hello there,
> 
> The problem seems to be related to the condition on line 61 of the `components/containers/ProjectsSection.vue` component. The condition checks if `projects.school.length` is defined. However, in this case, I’ve applied a regex filter to include only certain GitHub repositories based on their names (which follow a specific naming convention used for school projects). Since your repositories don't match this regex, `projects.school` is undefined, and the condition fails.
> 
> To resolve this, you can remove the `&& projects.school.length` condition from line 61. This should allow the GitHub repository information to render correctly in the “Personal Project” and “School Project” sections.
> 
> If you need further assistance or if there are any other issues, feel free to reach out.
> 
> Best regards, Jonathan

Thank you very much for your answer!
