### ISSUE TITLE
Consider Using CDN for Icons Instead of a Sprite Sheet

### ISSUE THREAD

**Issue by 4444TENSEI** [JonathanXDR/Application-Website-Frontend#70]
I was wondering if you would consider using a CDN to serve the icons instead of using a sprite sheet?   Here are a few reasons why this might be beneficial:

Performance Improvement: CDN-hosted icons can be cached and delivered more quickly to users around the world, reducing load times and improving overall performance.
Selective Loading: With individual icons, users can load only the icons they need for a particular page or component, rather than downloading an entire sprite sheet that may contain unused icons.
Easier Maintenance: Managing a sprite sheet can be cumbersome, especially as the number of icons grows.   CDN hosting allows for easier updates and additions to the icon set without the need to recompile a sprite sheet.
Browser Caching: Browsers can cache individual icons from a CDN, which means that once an icon is loaded, it doesn’t need to be re-downloaded on subsequent visits, further improving load times.
Scalability: As the project grows, the sprite sheet can become bloated and less efficient.   CDN hosting scales better with the size of the project and the number of icons.
Compatibility: Some browsers may have issues with large sprite sheets, and using a CDN can mitigate these compatibility issues.
I understand that this might be a significant change, but I believe it could greatly enhance the user experience and maintainability of the project.   What are your thoughts on this approach?

Thank you for considering this suggestion.

**Comment by JonathanXDR** [comment]
Thank you for your detailed suggestion regarding the use of a CDN for serving icons instead of a sprite sheet. I appreciate the time you've taken to highlight the potential benefits of this approach. I'll need some time to evaluate this suggestion in the context of the current project setup and future plans. I'll investigate the feasibility and potential benefits of implementing this change. If the advantages outweigh the effort required for implementation, I'll certainly consider making this switch. I'll provide an update once I've had the opportunity to fully evaluate your proposal.

**Comment by JonathanXDR** [comment]
Thank you for waiting while I considered the best approach for this issue. I’ve decided to switch to an Iconify custom icon collection using the `@nuxt/icon` module instead of implementing a custom CDN. This approach is significantly less effort while still providing a robust solution for managing icons.

That said, I’ll need to wait for the resolution of [[nuxt/icon#265](https://github.com/nuxt/icon/issues/265)](https://github.com/nuxt/icon/issues/265), as the current implementation doesn’t support icon names separated by dots, which is required for my project. Once that issue is resolved, I’ll proceed with the migration.

Thanks again for your patience and understanding! If you have any further suggestions or ideas, feel free to share them.
